version: "3.9"
services:
  api:
#    build:
#      context: .
    image: shurxet/django_app
    ports:
    - 80:80
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: python manage.py runserver 0.0.0.0:80
  migrations:
#    build:
#      context: .
    image: shurxet/django_app
    depends_on:
      pg:
        condition: service_healthy
    command: python manage.py migrate


  pg:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 20s
      retries: 20
