# Generated by Django 4.1.7 on 2023-02-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='compilation',
            new_name='items',
        ),
    ]
